name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://douglarek:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Build package
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go env -w GOPRIVATE="github.com/douglarek/beats-processors"
          curl -LO https://gist.githubusercontent.com/douglarek/11ba3b7b2cc39a1219640a0dbdce3990/raw/71ce4d820d91be3171a4dcf2d6d81cdc4742f6c6/imports_common.go.patch
          patch -p0 < imports_common.go.patch
          curl -LO https://gist.githubusercontent.com/douglarek/d2196cb214ee70471f1654a82317ff43/raw/00d2e81a2c5e8a54b0e0daf41e1b27c584ad1959/filebeat_main.patch
          patch -p0 < filebeat_main.patch
          git diff
          go mod tidy -compat=1.18
          make mage
          cd filebeat
          env CGO_ENABLED=0 mage package
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            filebeat/build/distributions/*
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load docker image
        run: docker load < filebeat/build/distributions/filebeat-*.docker.tar.gz
      - id: get-tag
        run: |
          tag=$(echo ${{ steps.vars.outputs.tag }} | cut -d- -f1 | cut -dv -f2)
          echo "::set-output name=tag::$tag"
      - name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: docker.elastic.co/beats/filebeat-oss:${{ steps.get-tag.outputs.tag }}
          dst: |
            ghcr.io/${{ github.repository_owner }}/filebeat-oss:${{ steps.vars.outputs.tag }}

